---
title: "AAA Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    theme: paper
runtime: shiny
navbar:
      - { title: "Report", href: "https://google.com", align: right, icon: ion-earth}
      - { title: "About ..", href: "https://google.com", align: right, icon: fa-lightbulb}
---

```{r}
htmltools::includeHTML("custom_header.html")
htmltools::includeHTML("footer.html")
```

```{r setup-packages, include=FALSE}
library("tidyverse")
library("rlang")
library("here")
library("data.table")
library("plotly")
library("flexdashboard")  
library("joyn")
library("gghighlight")
library("DT")
library("RColorBrewer")
library("highcharter")
library("ggrepel")
library("ggtext")
library("zoo")
library("collapse")
```

PAGE1 {#page1}
===========================================================

Sidebar {.sidebar data-width=250}
-----------------------------------------------------------------------

```{r}
selectInput("plot_which_trend", 
                   label = "Plot:",  
                   choices = c(
                     "Regional aggregates", 
                     "Selected economies", 
                     "Both"
                   ), 
                   selected = c("Regional aggregates"), 
                   multiple = FALSE
)
```

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Tab 1 

### Tab2

PAGE2 {#page2}
===========================================================

Sidebar {.sidebar data-width=250}
-----------------------------------------------------------------------

```{r}

selectInput(
  "level_or_growth_decomposition", 
  label     = "Level or growth decomposition:", 
  choices   = c(
    "Level", 
    "Growth"
  ), 
  selected  = "Level", 
  multiple = FALSE
)

```

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Visualization

### Explanation

PAGE3
===========================================================


Sidebar {.sidebar data-width=200}
-----------------------------------------------------------------------

```{r}
selectInput("plot_which_change", 
                   label = "Plot:",  
                   choices = c(
                     "Regional aggregates", 
                     "Countries"
                   ), 
                   selected = c("Regional aggregates"), 
                   multiple = FALSE)

```

Column {.tabset .tabset}
-----------------------------------------------------------------------

### Plot

Column {.tabset data-width=200}
-----------------------------------------------------------------------
### Explanation

PAGE4
===========================================================

Sidebar {.sidebar data-width=200}
-----------------------------------------------------------------------

```{r}
selectInput("ineq_indicatorX", 
            label = "Indicator x-axis:",
            choices = c(
              "Prosperity Gap",
              "Mean", 
              "Mean - Bottom 40", 
              "(PG) Inequality"
            ),
            selected = "Mean")
```

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Plot

<!-- Column {.tabset data-width=200} -->
<!-- ----------------------------------------------------------------------- -->

### Explanation

About and Definitions {#tab_about}
===========================================================

Column {.tabset}
-----------------------------------------------------------------------

### About Page {#About}
### Definitions {#Definitions}

